version: '3.5'

services:
  margatsni-service:
    container_name: margatsni-service-container
    build: .
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8080:8080"
    command: bash -c "npm i && npm run heroku-postbuild && npm start"
